### ISSUE TITLE
Added some Animated icons to beautify the look

### ISSUE THREAD

**Issue by SadafKausar2025** [Sahil1786/Petari#103]
**Is your feature request related to a problem? Please describe.**
No it not related to problem

**Describe the solution you'd like**
this new animated icons gives new good look to the home page and Navbar

**Describe alternatives you've considered**

**Additional context**
video record is here

https://github.com/Sahil1786/Petari/assets/137484958/c05e7770-1e5d-431f-9a25-913e5e38f281

**Comment by SadafKausar2025** [comment]
Can you please assign me this issue ?
I am Gssoc'24 contributors

**Comment by Sahil1786** [comment]
You have to send again the pr request
