### ISSUE TITLE
userSignup not working properly

### ISSUE THREAD

**Issue by DebmalyaKuila** [Sahil1786/Petari#107]
**Description**
user signup page doesn't seem to be working properly, after submitting user signup form ,there seems to be be an internal server error

**Steps to reproduce**
1. Go to Login page
2. Click on sign up and fill the form in signup page 
3. Click submit
4. you will see an internal server error

**Expected behavior**
after clicking the submit button , user should be redirected to userDashboard Page

**Screenshots**
![Screenshot (3)](https://github.com/Sahil1786/Petari/assets/132048232/0b030db1-911d-43fd-96d0-8d9f8e0cf436)

**Desktop (please complete the following information):**
 - OS: Windows11
 - Browser : Chrome 
 - Version 124.0.6367.208 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: Oneplus 11R
 - OS: OxygenOs 14
 - Browser Chrome

**Additional context**
1.I came across this problem while working on issue number  #18   and I have already solved the user signup issue . I'm creating a new issue so that I can create a pull request.
2.There seems to be a problem with donationRoutes and the server was getting crashed. That's why I have commented that part in app.js

**lebals :**
please add gssoc24 label with this issue

**Comment by AkshitLakhera** [comment]
Please assign this issue to me with appropriate gssoc'24 label

**Comment by ekkaaditya200** [comment]
I want to work on this issue can you please assign it to me.
