### ISSUE TITLE
Subscribe mail using node mailer

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Sahil1786/Petari#114]
**Is your feature request related to a problem? Please describe.**
Subscribe mail using node mailer
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by RamakrushnaBiswal** [comment]
hi @Sahil1786 can you assign it to me?

**Comment by nishant0708** [comment]
Hello , I'm interested in contributing to the project by implementing Support Us functionality. Could you please assign this task to me under GSSoC'24 with appropriate level?

**Comment by Dhevamuthu** [comment]
I have already done projects using nodemailer. So please provide this task to me under GSSOC 2024

**Comment by K-21** [comment]
@RamakrushnaBiswal @Sahil1786 can you please assign this to me

**Comment by Hemu21** [comment]
@Sahil1786  can you please assign this to me.
