### ISSUE TITLE
Add Code of Conduct 

### ISSUE THREAD

**Issue by Princegupta101** [Sahil1786/Petari#13]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow these instructions on how to add a Code of Conduct.

Sample: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/CODE_OF_CONDUCT.md

**Comment by harikavaleti911** [comment]
Hello sir
I am ready to create code of conduct for this project.
Please assign this issue to me.

**Comment by Sahil1786** [comment]
@harikavaleti911  I am assigning you on this work

**Comment by harikavaleti911** [comment]
Thank you for your response sir.
Sir how can I reach out you after completion of this task sir?

**Comment by harikavaleti911** [comment]
Sir I have added the code of conduct sir and sent a pull request to accept it.
Can we merge now sir
