### ISSUE TITLE
password strength feature

### ISSUE THREAD

**Issue by Samani-Humaira** [Sahil1786/Petari#135]
**Is your feature request related to a problem? Please describe.**

creating a password strength feature so that when user go for signup he should add a strong password that will be hard to crack.

**Describe the solution you'd like**

Users are currently able to sign up with the password "1234," but an error should be implemented to ensure they sign up with a stronger password.

Creating a feature to ensure that users log in with a strong password is very important.

Hey @Sahil1786 please assign me this under GSSOC'24

**Comment by LEARNER-dakshesh** [comment]
Hey @Sahil1786  can you please assign me this issue . I can work with it .

**Comment by Maheshwari-Love** [comment]
@Samani-Humaira can we collaborate in this if you want to, that will be new learning for me to code together and get the github badges as award of learning
