### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Sahil1786/Petari#15]
I see in your website not a proper landing page
i want to add this
tech stack to be used
-aos.js
-ityped.js
-tilt.js

**Comment by Pruthaa17** [comment]
Hello !! Under GSSOC'24 , I believe that I'll be able to make the complete landing page keeping it simple yet attractive by using HTML ,CSS ,Bootstrap and  React js. I'll consider working on the Color Scheme and emphasis more on the quality of the content. @Sahil1786

**Comment by balimpuramvikasgoud** [comment]
@RamakrushnaBiswal 

hi there i am newbie can you tell how to open landing page ..

**Comment by RamakrushnaBiswal** [comment]
@balimpuramvikasgoud landing page means when you open the website what ever you see that

**Comment by Sahil1786** [comment]
Yes

**Comment by Pruthaa17** [comment]
![Screenshot (363)](https://github.com/Sahil1786/Petari/assets/141839876/01295da8-cfba-4b5f-ba34-b961b3fcdf5c)
![Screenshot (366)](https://github.com/Sahil1786/Petari/assets/141839876/504bed88-50f9-4df2-9f9c-84e030a77a24)
![Screenshot (364)](https://github.com/Sahil1786/Petari/assets/141839876/e16bd422-087e-40aa-91ce-1a227b104a8b)
![Screenshot (367)](https://github.com/Sahil1786/Petari/assets/141839876/48e41639-80a7-48ac-b2ce-322002703728)


1. About US and Vision - heading are aligned in the center
2. Made the About to look attractive by aligning the text in the center and reducing the image size 
3. Added bg color to Contact Me 
4. Made the submit button look attractive 


Can I create a pull request for these changes ?

**Comment by RamakrushnaBiswal** [comment]
@Pruthaa17 use bootstrap for styling
