### ISSUE TITLE
Adding Hovering effect in Donate Now 

### ISSUE THREAD

**Issue by namandude** [Sahil1786/Petari#158]
Hey !!
I am raising the issue for the feature i want to add on is hovering effect on the Donate now button .
![image](https://github.com/Sahil1786/Petari/assets/118013565/c0e9d199-1e01-4ea8-935f-6646f2305600)

It will add up additional starts to your already beautiful looking website .

If someone click or take their cursor on donate now it shows some animated effect . 

Could you please assign this me under gssoc so that i can immediately start working upon this. 
Thank You!1

**Comment by pulkit49** [comment]
Please assign me this issue under GSSOC 2024.

**Comment by pragneshborad** [comment]
I would like to work on this issue @Sahil1786 , please assign me this issue.

**Comment by namandude** [comment]
Hey Please assign this me as soon as possible so that i can start working on this
