### ISSUE TITLE
 Refactoring Needed - Decoupling Functions, Routes, and Controllers from app.js

### ISSUE THREAD

**Issue by SouptikTaran** [Sahil1786/Petari#16]
The current `app.js` file houses all functions, routes, controllers, and even nodemailer implementations, resulting in a cluttered and unmanageable codebase. To enhance maintainability and scalability, we propose refactoring by decoupling these components from `app.js` and organizing them into separate modules or directories. This approach will improve readability, facilitate code reuse, and foster easier collaboration among developers.

Solutions :
1. Separate Concerns: Move functions, routes, controllers, and nodemailer implementations into distinct modules.
2. Modularization: Organize code into smaller, reusable components for improved maintainability.
3. Refactor `app.js`: Restructure `app.js` to serve as the main entry point, delegating functionality to separate modules.
4. Documentation: Update project documentation to reflect the new structure and guide developers.

Feedback and Contributions Welcome

**Comment by Sahil1786** [comment]
Do you want contribute on this  ?

**Comment by SouptikTaran** [comment]
Absolutely! As a member of GSSOC (GirlScript Summer of Code), I'm keen to contribute to this effort. Improving the project's folder structure aligns well with the goals of enhancing maintainability and fostering a more collaborative development environment. I'm eager to dive in and lend a hand to make these improvements happen.

**Comment by Sahil1786** [comment]
I will assign you by tonight

**Comment by princeragh1801** [comment]
Hello @Sahil1786 
I also want to contribute on the same issue. Can I ?

**Comment by Sahil1786** [comment]
guys you can contribute now
