### ISSUE TITLE
Creating 404 not found page with config

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Sahil1786/Petari#167]
**Is your feature request related to a problem? Please describe.**
Creating 404 not found page with config

**Describe the solution you'd like**
mean when user send any request to unknown URL it show that page

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/Sahil1786/Petari/assets/125277258/e788bd10-d59e-40f0-9163-3a42bff6d622)
What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Shoaibxaif** [comment]
@Sahil1786 With a strong proficiency in UI/UX, I am confident that I can significantly improve the user experience and visual appeal of your online presence. I am eager to apply my skills to this project and believe that my expertise makes me an ideal candidate for this task
