### ISSUE TITLE
Hamburger menu is not responsive

### ISSUE THREAD

**Issue by Praveenkumar5048** [Sahil1786/Petari#177]
**Describe the bug**
The hamburger menu present in the side bar is not responsive. What I meant is when this Triple bar hamburger icon is clicked the side bar opens up but this hamburger icon doesn't get changed to a cross mark.

**To Reproduce**
1. Login to the appllication
2. Click on hamburger icon near the dashbord
3. Now the sidebar opens up but the humberger should have changed to "X" mark

**Expected behavior**
The toggle between Humberger icon and "X" icon will create better user experiance

**Screenshots**
![Screenshot 2024-06-14 102421](https://github.com/Sahil1786/Petari/assets/147526027/5bff693e-596c-4fd8-a432-46f3e3bf2c90)

**Additional context**
Please assign this task to me I will complete this.

**Comment by Riyasharma1311** [comment]
please assign me this issue
