### ISSUE TITLE
need  to be resolve the ejs file

### ISSUE THREAD

**Issue by gantasrilaitha** [Sahil1786/Petari#211]
need  to be resolve the ejs file 
![Screenshot 2024-07-03 162546](https://github.com/Sahil1786/Petari/assets/111786720/6610256c-3b94-4e3d-924e-43e14747ccf7)

_Originally posted by @Sahil1786 in https://github.com/Sahil1786/Petari/issues/203#issuecomment-2205792159_

**Comment by Sahil1786** [comment]
i need aslo backend
