### ISSUE TITLE
Color combinations do not coordinate .

### ISSUE THREAD

**Issue by aasthakourav20** [Sahil1786/Petari#22]
The website pages looks quite unattractive , color combinations do not coordinate . Hey Sahil1786  , I would like to add some styles / designs to make it more attractive . Please assign this task to me .

**Comment by Siddhi0504** [comment]
hi,can you assign this task to me?

**Comment by aasthakourav20** [comment]
Hey @Sahil1786 , the link you provided for Petari app isn't working , would you please help regarding this .
![Uploading Screenshot (197).png…]()

**Comment by Sahil1786** [comment]
Can you share one more time .. image is not visible

**Comment by aasthakourav20** [comment]
Yes sure ...
![Uploading IMG20240512173554.jpg…]()

**Comment by Sahil1786** [comment]
Still image not visible to me

**Comment by Sahil1786** [comment]
You connect me via LinkedIn
