### ISSUE TITLE
admin  login error 

### ISSUE THREAD

**Issue by Sahil1786** [Sahil1786/Petari#28]
need to fix the admin login error

**Comment by geeky2502** [comment]
Can Elaborate the problem @Sahil1786 . Explain the  problem more precisely

**Comment by Prateek579** [comment]
@Sahil1786 please assign me this issue

**Comment by Sahil1786** [comment]
Thare is a error on code .. whan admin trying to logs showing user password invalid .

**Comment by DebmalyaKuila** [comment]
Hey @Sahil1786 , assign me this issue .

**Comment by Komalpardasani** [comment]
please assign me this issue

**Comment by DebmalyaKuila** [comment]
Hey , 
Could you change the label as "gssoc" , due to this reason I'm having some issues in GSSOC system .

**Comment by DebmalyaKuila** [comment]
Thanks for adding the gssoc label , but having two levels might cause some issues , I would like you to remove one one the level1 or level2
