### ISSUE TITLE
Regarding the UI

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Sahil1786/Petari#3]
I am a contributor GSSOC 2024,Assign me this project to i complete all the things then i can move for backend🙂,
-Header logo
-Navbar 
-Logo with anchor tag
-Hover effect in Logo
-Arranging HTML elements
-Font Family
-Also REsponsive

**Comment by Anikketsingh** [comment]
i would like to work on this please assign it to me @RamakrushnaBiswal

**Comment by Sahil1786** [comment]
guys you can contribute now

**Comment by Anikketsingh** [comment]
Thank you @Sahil1786 for assigning this project  to me , will work on the ui part and will make the website visually pleasing

**Comment by dhananjaysingh10** [comment]
Hi @Sahil1786 , UI of the website is one of the most important things. Having knowledge of the tech stack used in the project and UI/UX designing, I think I can contribute to the project. I, along with other contributors, can make the UI more attractive, engaging, and provide a good user experience. Can you please assign this task to me?

**Comment by RamakrushnaBiswal** [comment]
issue solved with the PR #115
