### ISSUE TITLE
Punctuation mistakes in the description.

### ISSUE THREAD

**Issue by anushkamahajan901** [Sahil1786/Petari#36]
![image](https://github.com/Sahil1786/Petari/assets/85194446/a7059d40-a459-42e3-b315-45ee28be5bdb)
![Screenshot 2024-05-12 142705](https://github.com/Sahil1786/Petari/assets/85194446/5628a308-a7ef-41cc-9bc6-72747f19b40e)

**Comment by alishasingh06** [comment]
@Sahil1786 please assign this issue to me

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Thank you! 🚀

**Comment by Techkunjan** [comment]
Can you kindly assign the task ?
