### ISSUE TITLE
Add google map api

### ISSUE THREAD

**Issue by Prachiii8287** [Sahil1786/Petari#41]
To find nearby needy ngo,google map apis are best

**Comment by Prachiii8287** [comment]
@Sahil1786 Please assign me this work.Check my repo I have already done work this kind of project so you will like more additional feature like this.

**Comment by Prachiii8287** [comment]
@Sahil1786 I am working under gssoc and contribute to your idea.

**Comment by Prachiii8287** [comment]
@Sahil1786 I am working under gssoc and want to  contribute to your idea.

**Comment by Sahil1786** [comment]
Thank you @Prachiii8287 for your response . I am assigning you

**Comment by Prachiii8287** [comment]
@Sahil1786 THANK YOU
