### ISSUE TITLE
Adding the list of nearby NGO's according to your location 

### ISSUE THREAD

**Issue by Srishtiii19** [Sahil1786/Petari#47]
Google maps API will fetch the list of nearby NGO's, then list of those NGO's will be shown below it. I can make it responsive uisng tailwind css

**Comment by Sahil1786** [comment]
@Srishtiii19, I have assigned you. Now, you can contribute.

**Comment by Srishtiii19** [comment]
sure @Sahil1786 on it! thankkyou!
