### ISSUE TITLE
Adding icons on navbar

### ISSUE THREAD

**Issue by Soumya6Tiwari** [Sahil1786/Petari#7]
in the navbar , adding of icons for different sections such as home, about us , contact would enhance it.

**Comment by Soumya6Tiwari** [comment]
@Sahil1786  kindly assign me this issue under gssoc'24

**Comment by GitNinja-bcd** [comment]
@Sahil1786 Please assign me this issue under gssoc'24

**Comment by Soumya6Tiwari** [comment]
@Sahil1786 kindly assign me this issue

**Comment by debasmi** [comment]
kind;y assign me this issue under gssoc 24 since i am a coursera certifies front end developer

**Comment by aasthakourav20** [comment]
@Sahil1786 kindly assign me this issue under GSSoC'24  , I have better experience with styling navbars

**Comment by SalehaTabassum** [comment]
@Sahil1786 please assign this issue to me

**Comment by Sajiyasiddiqui** [comment]
I want to work on this project .please assign to me.

**Comment by Sahil1786** [comment]
guys you can contribute now

**Comment by Missdivyaa** [comment]
@Sahil1786 I want to work on this issue. kindly assign me this issue under gssoc'24
