### ISSUE TITLE
(GSSoC'24)Restructure App.js for Improved Readability and code maintainability 

### ISSUE THREAD

**Issue by DebmalyaKuila** [Sahil1786/Petari#8]
App.js file is overly large, hindering readability and maintainability. Proposal to refactor the codebase  into smaller, modular components for better organization and understanding. 

Assignees: Assigned me this issue.

**Comment by Sahil1786** [comment]
Ok ..I am assigning you .

**Comment by ekayZ7875** [comment]
As i looked to app.js i just findout that all the controllers along with routes are written under it which makes it bulky.

Proposed Solution:
1.I will make a separate folder for controllers.
2.Next I will make separate folder for routes too.

**Comment by DebmalyaKuila** [comment]
Hey, 
Could you add "gssoc" lable in this issue  because I'm having some issues regarding gssoc24 leaderboard
