### ISSUE TITLE
Add CONTRIBUTING.md file to repository

### ISSUE THREAD

**Issue by thevijayshankersharma** [Sahil1786/Petari#86]
Currently, the repository lacks a CONTRIBUTING.md file, which serves as a crucial guide for potential contributors on how to effectively participate in the project. The absence of this file makes it challenging for new contributors to understand the project's contribution guidelines, coding standards, and other important information.

**Comment by alishasingh06** [comment]
@Sahil1786 pls assign this issue to me and add labels. I have the contributing.md file ready.

**Comment by suhanipaliwal** [comment]
Please assign me this issue. I would like to work on it.
